device: cuda:0
experiment_dir: /glade/u/home/jmelms/projects/dcmip2025_idealized_tests/experiments/A.mass_conservation/data
experiment_name: canonical_run
ic_dates:
- 2018/01/01 12:00
- 2018/07/01 12:00
- 2019/01/01 12:00
- 2019/07/01 12:00
keep_vars: None
n_timesteps: 360
